const PLATFORM_SERVER_BASE_URL = '{PLATFORM_SERVER_BASE_URL}';
const AUTH0_DOMAIN = '{AUTH0_DOMAIN}';
const AUTH0_CLIENT_ID = '{AUTH0_CLIENT_ID}';

export {
  PLATFORM_SERVER_BASE_URL,
  AUTH0_DOMAIN,
  AUTH0_CLIENT_ID,
};
