name: Floret Platform CI

on: [push]

jobs:
  deploy:
    name: Deploy Platform via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Add known hosts
      run: ssh-keyscan -H 54.221.104.12 >> ~/.ssh/known_hosts
    - name: Deploy Platform version
      run: ssh -i ~/.ssh/id_rsa ec2-user@54.221.104.12 "/home/ec2-user/app/scripts/restart.sh 0.0.5"
